I did some stuff
VoigtSebastian/rust-auth-service pull request #8
Opened 2021-06-20 16:05 UTC by VoigtSebastian

2021-06-20 16:19 UTC, VoigtSebastian commented
I will fix this later

2021-06-20 17:10 UTC, VoigtSebastian commented
I installed [rust-hook](https://crates.io/crates/rusty-hook) which seems like a very interesting crate.

2021-06-21 18:09 UTC, VoigtSebastian commented
This pr will close #5 and #7 when merged

2021-06-21 19:24 UTC, VoigtSebastian commented
Turns out, if you want to upgrade sqlx to version 0.5 you will have to upgrade actix-web and actix-rt.
This breaks the middleware implementation and the current documentation of actix-web 4 (beta) isn't great.

2021-06-25 21:33 UTC, b-faller requested changes
Looks good so far.

2021-06-25 21:33 UTC, b-faller commented on .github/workflows/test-all.yml
> +          args: --workspace --doc
The doc argument can be dropped. See the comment in #7.

2021-06-25 21:33 UTC, b-faller commented on automation.sh
> +    cargo test --workspace --doc
We could use `cargo test --workspace -- --include-ignored` (#7).

2021-06-25 21:46 UTC, b-faller approved these changes

2021-06-25 21:46 UTC, merged